version: '3.8'

services:
  mongo-db:
    image: mongo:latest
    ports: 
      - "27017:27017"
    networks:
      - app-network

  express-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongo-db

networks:
  app-network:
    driver: bridge